from pydantic import BaseModel, EmailStr
from datetime import datetime
from typing import List, Optional, Dict, Any
from uuid import UUID

# Shared properties
class UserBase(BaseModel):
    email: EmailStr
    name: Optional[str] = None
    demographics: Optional[Dict[str, Any]] = None

# Properties to receive on user creation
class UserCreate(UserBase):
    user_id: str # This will be the Auth0 sub

# Properties to return to client
class User(UserBase):
    user_id: str

    class Config:
        from_attributes = True # Formerly orm_mode

# This is the 'base' model for a problem.
# It defines the fields that are common for creating and reading.
class ProblemBase(BaseModel):
    title: str
    description: Optional[str] = None
    difficulty: Optional[str] = None
    author: Optional[str] = None
    file_path: str
    tags: Optional[List[str]] = None
    update_log: Optional[List[Any]] = None

# This model is used when reading a problem from the database.
# It includes fields that are generated by the DB, like `problem_id`.
class Problem(ProblemBase):
    problem_id: UUID
    created_at: datetime

    # This tells Pydantic to read data from ORM models (like your 'Problem' class)
    class Config:
        from_attributes = True

# This is for the response of the single problem endpoint
class ProblemDetail(BaseModel):
    metadata: Problem
    markdown_content: str
